"""phase5 migration provenance fields

Revision ID: 0659300da7ab
Revises: f1b72b3aaa0f
Create Date: 2026-08-05 22:23:34.192259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0659300da7ab'
down_revision: Union[str, Sequence[str], None] = 'f1b72b3aaa0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('migration_source', sa.String(length=50), nullable=True))
    op.add_column('bookings', sa.Column('migration_external_ref', sa.String(length=100), nullable=True))
    op.add_column('bookings', sa.Column('migration_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_unique_constraint('uq_booking_migration_ref', 'bookings', ['migration_source', 'migration_external_ref'])
    # server_default needed here: existing rows (Hamilton's real spaces)
    # have no value for this new NOT NULL column otherwise.
    op.add_column('spaces', sa.Column('is_bookable', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spaces', 'is_bookable')
    op.drop_constraint('uq_booking_migration_ref', 'bookings', type_='unique')
    op.drop_column('bookings', 'migration_snapshot')
    op.drop_column('bookings', 'migration_external_ref')
    op.drop_column('bookings', 'migration_source')
    # ### end Alembic commands ###
