"""phase1 initial schema

Revision ID: 0c9d43631866
Revises: 
Create Date: 2026-08-05 21:27:56.423332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c9d43631866'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Needed for GIST support on the space_id (UUID) equality term of the
    # double-booking exclusion constraint on bookings, below.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contacts_email_lower', 'contacts', [sa.literal_column('lower(email)')], unique=False)
    op.create_table('venues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('spaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('min_food_spend', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('standard_min_adults', sa.Integer(), nullable=False),
    sa.Column('wheelchair_accessible', sa.Boolean(), nullable=False),
    sa.Column('has_per_head_shortfall_fee', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'name', name='uq_space_venue_name')
    )
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('space_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('time_range', postgresql.TSRANGE(), sa.Computed("tsrange(event_date + start_time, event_date + end_time, '[)')", persisted=True), nullable=True),
    sa.Column('status', sa.Enum('enquiry', 'offered', 'tentative', 'confirmed', 'completed', 'cancelled', 'dead', name='booking_status'), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('adult_count', sa.Integer(), nullable=False),
    sa.Column('child_count', sa.Integer(), nullable=False),
    sa.Column('reference_code', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('space_id'), '='), (sa.column('time_range'), '&&'), where=sa.text("status NOT IN ('cancelled', 'dead')"), using='gist', name='excl_booking_space_time_overlap'),
    sa.CheckConstraint('end_time > start_time', name='ck_booking_end_after_start'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_code')
    )
    op.create_table('booking_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # booking_events is append-only: reconstructing "how did we get here"
    # must never be foiled by a row having been quietly edited or removed.
    op.execute(
        """
        CREATE FUNCTION prevent_booking_events_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'booking_events is append-only: % is not permitted', TG_OP;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_booking_events_no_update
        BEFORE UPDATE ON booking_events
        FOR EACH ROW EXECUTE FUNCTION prevent_booking_events_mutation()
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_booking_events_no_delete
        BEFORE DELETE ON booking_events
        FOR EACH ROW EXECUTE FUNCTION prevent_booking_events_mutation()
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS trg_booking_events_no_delete ON booking_events")
    op.execute("DROP TRIGGER IF EXISTS trg_booking_events_no_update ON booking_events")
    op.execute("DROP FUNCTION IF EXISTS prevent_booking_events_mutation()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_events')
    op.drop_table('bookings')
    op.drop_table('spaces')
    op.drop_table('venues')
    op.drop_index('ix_contacts_email_lower', table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###

    # op.drop_table() does NOT drop the Postgres ENUM type it created for
    # the 'status' column -- found by testing a full downgrade-then-
    # upgrade round trip, where the leftover type made CREATE TYPE fail
    # on re-upgrade. Doesn't affect Railway (upgrade-only deploys), but a
    # real bug for anyone running downgrade locally.
    op.execute("DROP TYPE IF EXISTS booking_status")

    op.execute("DROP EXTENSION IF EXISTS btree_gist")
