"""phase2 documents

Revision ID: b2e12da96d5e
Revises: 0c9d43631866
Create Date: 2026-08-05 21:40:50.991833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2e12da96d5e'
down_revision: Union[str, Sequence[str], None] = '0c9d43631866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('agreement', 'beo', name='document_type'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'viewed', 'signed', name='document_status'), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('access_token', sa.String(length=64), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signer_name', sa.String(length=255), nullable=True),
    sa.Column('signer_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('booking_id', 'type', 'version', name='uq_document_booking_type_version')
    )
    op.create_index('uq_document_current_per_booking_type', 'documents', ['booking_id', 'type'], unique=True, postgresql_where=sa.text('is_current'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_document_current_per_booking_type', table_name='documents', postgresql_where=sa.text('is_current'))
    op.drop_table('documents')
    # ### end Alembic commands ###

    # See phase1's downgrade() for why this is needed: op.drop_table()
    # does not drop the Postgres ENUM types it created.
    op.execute("DROP TYPE IF EXISTS document_type")
    op.execute("DROP TYPE IF EXISTS document_status")
