"""phase4 nullable times and lead capture fields

Revision ID: f1b72b3aaa0f
Revises: 296988e69909
Create Date: 2026-08-05 22:05:32.845139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1b72b3aaa0f'
down_revision: Union[str, Sequence[str], None] = '296988e69909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('proposed_time_slot', sa.String(length=100), nullable=True))
    op.add_column('bookings', sa.Column('lead_source', sa.String(length=50), nullable=True))
    op.add_column('bookings', sa.Column('lead_referrer', sa.String(length=500), nullable=True))
    op.alter_column('bookings', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('bookings', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    # ### end Alembic commands ###

    # Only tentative/confirmed/completed bookings should actually reserve
    # the space -- enquiries and offers must be able to coexist for the
    # same date so a second lead isn't silently refused. Autogenerate
    # doesn't diff ExcludeConstraint predicates, so this is manual.
    op.execute("ALTER TABLE bookings DROP CONSTRAINT excl_booking_space_time_overlap")
    op.execute(
        """
        ALTER TABLE bookings ADD CONSTRAINT excl_booking_space_time_overlap
        EXCLUDE USING gist (space_id WITH =, time_range WITH &&)
        WHERE (status IN ('tentative', 'confirmed', 'completed'))
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("ALTER TABLE bookings DROP CONSTRAINT excl_booking_space_time_overlap")
    op.execute(
        """
        ALTER TABLE bookings ADD CONSTRAINT excl_booking_space_time_overlap
        EXCLUDE USING gist (space_id WITH =, time_range WITH &&)
        WHERE (status NOT IN ('cancelled', 'dead'))
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('bookings', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.drop_column('bookings', 'lead_referrer')
    op.drop_column('bookings', 'lead_source')
    op.drop_column('bookings', 'proposed_time_slot')
    # ### end Alembic commands ###
